@test "verifies the template is in place" {
  grep -q "generated by limits cookbook" /etc/security/limits.conf 
}

# This is expected to *not* be found
@test "filtered limits are excluded" {
  test $(grep -c "notlegit" /etc/init/runsvdir.conf) -eq 0
}