AllCops:
  Includes:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Excludes:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
TrailingComma:
  Enabled: false
